version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: bundle install /build
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run:  bundle install /build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test