version: 2
jobs:
  build:
    docker:
      - image: circleci/yarn:6-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - yarn_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn ng build --prod --build-optimizer --no-progress
      - run: yarn ng test --single-run --no-progress